server:
  port: 8092
 #项目的发布路径是根目录(默认)
spring:     #定义springmvc视图解析器
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

#编辑dubbo配置
dubbo:
  scan:
    basePackages: com.jt
  application:
    name: consumer-web
  registry:
    address: zookeeper://192.168.198.130:2181?backup=192.168.198.130:2182,192.168.198.130:2183